version: '3.8'
services:
    eureka:
        container_name: eureka
        image: adoptnettech/adopt-eureka-server-image:V-2.1
        restart: always
        ports:
            - 8761:8761
        networks:
            - adopt-network
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
        environment:
          - TZ=Asia/Yangon
          - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://euraka:8761/eureka
          - server.ssl.enabled=false
          - server.ssl.key-store=/root/Cert1.pfx
          - server.ssl.key-store-type=pkcs12
          - server.ssl.key-store-password=secret
          - server.ssl.key-password=secret
        logging:
           driver: "json-file"
           options:
             max-size: "10m"
             max-file: "3"
        #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    zookeeper:
      container_name: zookeeper
      restart: always
      image: adoptnettech/zookeeper:latest
      environment:
        - ZOOKEEPER_CLIENT_PORT=2181
        - ZOOKEEPER_TICK_TIME=2000
        - ZOOKEEPER_SERVER_ID=1
        - ZOOKEEPER_PEER_PORT=2888
        - ZOOKEEPER_LEADER_PORT=3888
        - ZOOKEEPER_INIT_LIMIT=5
        - ZOOKEEPER_SYNC_LIMIT=2
        - ZOOKEEPER_SERVERS=0.0.0.0:2888:3888
      ports:
        - 2181:2181
        - 22181:22181
        - 2888:2888
        - 3888:3888
      volumes:
        - /var/lib/docker/zookeeper/log:/var/lib/zookeeper/log
        - /var/lib/docker/zookeeper/secrets:/etc/zookeeper/secrets
        - zookeeper:/var/lib/zookeeper/data
      user: root:root
      networks:
        - adopt-network
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    kafka:
      image: adoptnettech/kafka:latest
      restart: always
      container_name: kafka
      depends_on:
        - zookeeper
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.24.87:30084
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - KAFKA_LISTENER_NAME=PLAINTEXT://0.0.0.0:30084
        - KAFKA_LISTENER_PORT=29092
        - KAFKA_LISTENER_HOSTNAME=0.0.0.0
        - KAFKA_LISTENER_INTER_BROKER_SECURITY_PROTOCOL=PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_ZOOKEEPER_SYNC_TIME=3000
        - KAFKA_REPLICA_FETCH_MAX_BYTES=2000000000  # Increase to 1 GB
        - KAFKA_MAX_REQUEST_SIZE=2000000000        # Increase to 1 GB
        - KAFKA_LOG_MESSAGE_MAX_BYTES=2000000000   # 1 GB (log segment si
        - KAFKA_MESSAGE_MAX_BYTES=2000000000       # 1 GB (maximum messag
        - KAFKA_SOCKET_RECEIVE_BUFFER_BYTES=1048576000  # 1 GB (increase
        - KAFKA_SOCKET_SEND_BUFFER_BYTES=1048576000    # 1 GB (increase s
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
        - KAFKA_SOCKET_REQUEST_MAX_BYTES=1200000000
        - KAFKA_HEAP_OPTS=-Xms4G -Xmx16G
        - log.retention.hours=168  # Retain logs for 7 days
        - log.retention.bytes=1073741824  # Retain logs up to 1 GB
        - log.segment.bytes=1073741824  # Segment size of 1 GB
        - KAFKA_FETCH_MIN_BYTES=524288     # 512 KB
        - KAFKA_FETCH_MAX_BYTES=10485760   # 10 MB
        - KAFKA_MAX_PARTITION_FETCH_BYTES=10485760   # 10MB
        - KAFKA_ENABLE_AUTO_COMMIT=true    # Auto commit offsets
        - KAFKA_SESSION_TIMEOUT_MS=10000   # Detect slow consumers faster
        - KAFKA_HEARTBEAT_INTERVAL_MS=3000 # Prevent rebalancing issues
      user: root:root
      ports:
        - 29092:29092
        - 30084:30084
      volumes:
        - /var/lib/docker/kafka/logs:/var/lib/kafka/log
        - kafka:/var/lib/kafka/data
      networks:
        - adopt-network
      deploy:
        resources:
          limits:
            cpus: 4 # Set CPU limit to 4 cores
            memory: 6G  # Set memory limit to 8 gigabytes

    akhq:
      image: adoptnettech/kafkagui:latest
      restart: always
      container_name: akhq
      ports:
        - "8088:8080"
      environment:
        AKHQ_CONFIGURATION: |
          akhq:
            connections:
              kafka-cluster:
                properties:
                  bootstrap.servers: 192.168.24.87:30084
      depends_on:
        - kafka
      networks:
        - adopt-network
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    mysql:
      container_name: mysql
      image: adoptnettech/mysql-server:8.0
      restart: always
      hostname: mysql
      extra_hosts:
            - mysql:192.168.24.87
      ports:
        - 3306:3306
        - 33060:33060
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1 --max_connections=5000 --log_bin_trust_function_creators=1 --server_id=1 --binlog_checksum=NONE --gtid_mode=ON --enforce_gtid_consistency=ON --log_bin --log_slave_updates=ON --master_info_repository=TABLE --relay_log_info_repository=TABLE --transaction_write_set_extraction=XXHASH64 --user=mysql --skip-host-cache --skip-name-resolve --default_authentication_plugin=mysql_native_password --bind-address=0.0.0.0 --port=3306 --innodb_buffer_pool_size=17179869184
      security_opt:
        - seccomp:unconfined
      volumes:
        - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
        - dbdata:/var/lib/mysql
        - "/etc/localtime:/etc/localtime:ro"
      environment:
          - MYSQL_ROOT_PASSWORD=AD0PT@Tumil#!2024@HTI#2023#1421
          - TZ=Asia/Yangon
      networks:
        - adopt-network
      deploy:
        resources:
          limits:
            cpus: 8 # Set CPU limit to 4 cores
            memory: 8G  # Set memory limit to 8 gigabytes

    ProvisionPortal:
      container_name: adopt-ProvisionPortal-container
      image: adoptnettech/adopt-cust-acquisition-image:V-43  #39 #37 #35 #29
      #image: adoptnettech/adopt-cust-acquisition-image_qa:V-30
      restart: always
      ports:
       - 4210:80
      environment:
       - APIGATEWAY_IP_PORT=192.168.24.87:30085
       - USERNAME=superadmin      #admin@HTI
       - PASSWORD=superadmin@2021@SUPERADMIN #Adopt@1421
      networks:
       - adopt-network
      volumes:
       - "/etc/localtime:/etc/localtime:ro"

    apigatewaycommon:
      container_name: adopt-apigatewaycommon-container
      restart: always
      image: adoptnettech/adopt-commonapigw-image:V-2.779 #767 #753 #751 #749 #734 #731 #726 #703 #656 #636      #V-2.633   #611  #610 #608 #558 #552 #536 #516
      ports:
        - 30085:30085
        - 9137:9137
        - 9138:9138
      environment:
        - eureka_client_serviceurl_defaultzone=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptcommonapigateway?allowPublicKeyRetrieval=true&useSSL=false&autoreconnect=true&createDatabaseIfNotExist=true
        - spring.datasource.username=adoptcommonapigateway
        - spring.datasource.password=adoptcommonapigateway@1421
        - sandbox.secret=secret_live_uUm2xgne8ypNSKj8NcQ9FeUht66ovE51
        - sandbox.key=key_live_ldZF4r8GfEZwdB1vllGbbIc6W46pfqDv
        - server.ssl.enabled=false
        - server.port=30085
        - server.ssl.key-store=/root/certificate.pfx
        - server.ssl.key-store-type=pkcs12
        - server.ssl.key-store-password=Adopt@123
        - TZ=Asia/Yangon
        - logging.level.root=INFO
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - spring.servlet.multipart.max-file-size=20MB
        - spring.servlet.multipart.max-request-size=20MB
        - websocket.gui.endpoint=http://192.168.24.87:4202,http://192.168.24.87:5201
        - app.cors.allowed-origins=http://192.168.24.87:4200,http://192.168.24.87:4202,http://localhost:4300,http://localhost:4200,https://uat-anandaselfcare.ananda.com.mm,http://192.168.24.87:4203,http://192.168.24.87:4204,http://192.168.24.87:4201,https://uat-gui.ananda.com.mm,https://uat-apigatewaycommon.ananda.com.mm,https://uat-integration.ananda.com.mm
          #- JAVA_OPTS=-Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
          #- JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9137 -Dcom.sun.management.jmxremote.rmi.port=9138 -Djava.rmi.server.hostname=192.168.24.87
        - JAVA_OPTS='-Xms6g -Xmx10g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=4 -XX:G1HeapRegionSize=16m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10 -XX:+UseContainerSupport -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap.hprof -Xlog:gc*,gc+heap=info:file=/tmp/gc.log:time,uptime,level,tags'
        - JAVA_TOOL_OPTIONS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9137 -Dcom.sun.management.jmxremote.rmi.port=9138 -Djava.rmi.server.hostname=192.168.24.87'
        - spring.datasource.hikari.maximum-pool-size=350
        - spring.datasource.hikari.connection-timeout=300000
        - spring.datasource.hikari.minimum-idle= 35
        - spring.datasource.hikari.idle-timeout=10000
        - spring.datasource.hikari.max-lifetime= 600000
        - jwt.expiration.seconds=86400
        - GOOGLE_MAPS_API_KEY=AIzaSyBJMMItJT9bMQlbJK8RnXhHi5rLrICje0s
      networks:
        - adopt-network
      volumes:
        - adoptbssdoc:/var/document/
        - adoptbssdoc1:/var/document/read
        - /var/lib/docker/containers/adopt:/log
        - "/etc/localtime:/etc/localtime:ro"
        - "/root/docker/certificate:/root"
      deploy:
            resources:
                limits:
                    cpus: 8 # Set CPU limit to 4 cores
                    memory: 12G  # Set memory limit to 8 gigabytes

    cms:
      container_name: adopt-cms-container
      image: adoptnettech/adopt-apigw-image:V-2.1550  #1547 #1533 #1531 #1530  #1526  #1525 #1523 #1504 #1502 #1500 #1499 #1495 #1493 #1471 #1470 #1446 #1461 #1459 #1455 #1446 #1442 #1429 #1381 #1327   #V-2.1314
      restart: always
      ports:
        - 30086:30086
        - 165:161/udp
        - 9135:9135
        - 9136:9136
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptconvergebss?allowPublicKeyRetrieval=true&useSSL=false
        - billing.url=http://192.168.24.87:40081/AdoptBillingEngine
        - sandbox.secret=secret_live_uUm2xgne8ypNSKj8NcQ9FeUht66ovE51
        - sandbox.key=key_live_ldZF4r8GfEZwdB1vllGbbIc6W46pfqDv
        - server.ssl.enabled=false
        - server.ssl.key-store=/root/cert.pfx
        - server.ssl.key-store-type=pkcs12
        - server.ssl.key-store-password=secret
        - server.ssl.key-password=secret
        - spring.datasource.username=adoptconvergebss
        - spring.datasource.password=adoptconvergebss@1421
        - spring.enable.quotareset.scheduling=false
        - TZ=Asia/Yangon
        - server.port=30086
        - planexpiryjob=0 0 0 * * *
        - quotaexpiryjob=* */15 * * * *
        - cronjobtimeforrefundrelease=0 0 0 */3 * *
          #- scheduling.job2.cron=0 0/5 * * * ?
        - cronjobtimeforupdatecustomeranditsservice=0 2 0 * * ?
        - cronJobTimeForPlanExpiryNotification=0 0 0 * * ?
        - cronJobTimeForDunning=0 0 0 * * ?
        - cronJobTimeForPartnerCount=0 59 11 * * *
        - cronJobTimeForAutomatePayment=0 0 0/1 * * ?
        - cronJobTimeForReminderCafFollowUp=0 */30 * * * *
        - cronJobTimeForOverDueCafFollowUp=0 */30 * * * *
          #- cronJobTimeForTatOverDueMatrix=0 */1 * * * *
        - cronJobTimeForServiceHold=0 0 0 * * ?
        - cronjobforServiceResume=0 0 0 * * ?
        - cronjobtimeforquotaresetdaymidnight=0 58 23 * * ?
        - cronJobTimeForReassignTicket=0 0/59 * * * *
        - cronJobTimeForTatMatrix=0 0/59 * * * *
        - cronjobtimeforconnectiongenerate=0 0/1 * * * ?
        - javers.sqlSchemaManagementEnabled=true
        - logging.level.root=INFO
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - groovy.file.path=/root
        - spring.datasource.hikari.maximumPoolSize=300
        - redis.sentinel.master=mymaster
        - redis.sentinel.nodes=192.168.24.87:26379
        - instanceId=CMS_125   #for connection number scheduler
          #- JAVA_OPTS=-Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
          #- JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9135 -Dcom.sun.management.jmxremote.rmi.port=9136 -Djava.rmi.server.hostname=192.168.24.87
        - JAVA_OPTS="-Xms6g -Xmx10g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=4 -XX:G1HeapRegionSize=16m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10 -XX:+UseContainerSupport -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap.hprof -Xlog:gc*,gc+heap=info:file=/log/cms_gc.log:time,uptime,level,tags"
        - JAVA_TOOL_OPTIONS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9135 -Dcom.sun.management.jmxremote.rmi.port=9136 -Djava.rmi.server.hostname=192.168.24.87'
        - dbMinPool=50
        - dbMaxPool=300
        - dbIdleTime=15000
      networks:
         - adopt-network
      command:
           - mkdir -p /var/document/custdoc
           - mkdir -p /var/document/invoices
           - mkdir -p /var/document/trialinvoice
           - mkdir -p /var/document/commissions
           - mkdir -p /var/document/payments
           - mkdir -p /var/document/ticketdoc
           - mkdir -p /var/document/leaddoc
           - mkdir -p /var/document/partnerdoc
           - mkdir -p /var/document/assignInventoryDocPath
             #- exec java $JAVA_OPTS -jar /CustomerManagement.jar
      volumes:
       - adoptbssdoc:/var/document/
       - adoptbssdoc1:/var/document/read
       - /var/lib/docker/containers/adopt:/log
       - "/etc/localtime:/etc/localtime:ro"
       - /root/docker/newcerti/2023-24:/root
       - /home/adoptminss/mTLS_Certs:/var
      deploy:
        resources:
          limits:
            cpus: 8 # Set CPU limit to 4 cores
            memory: 12G  # Set memory limit to 8 gigabytes

    notification:
      container_name: adopt-notification-container
      image: adoptnettech/adopt-notification-image:V-2.372 #354 #357 #354 #342 #341 #318 #317 #314 #309 #301
      restart: always
      ports:
        - 9092:9092
        - 164:161/udp
        - 9131:9131
        - 9132:9132
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptnotification?allowPublicKeyRetrieval=true&useSSL=false&autoreconnect=true&createDatabaseIfNotExist=true
        - eureka.instance.ip-address=192.168.24.87
        - server.ssl.enabled=false
        - server.ssl.key-store=/root/Cert1.pfx
        - server.ssl.key-store-password=secret
        - server.ssl.key-password=secret
        - spring.datasource.username=adoptnotification
        - spring.datasource.password=adoptnotification@1421
        - TZ=Asia/Yangon
          #- logging.level.com.adopt==DEBUG
        - spring.profiles.active=kafka
        - logging.level.root=DEBUG
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - SMSHASUPPORT=false
        - server.port=9092
        - json.file.path=/root/firebase_config    #/home/adopt/push_notification
        - spring.enable.fcmService.scheduling=true
        - JAVA_OPTS=-Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
        - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9131 -Dcom.sun.management.jmxremote.rmi.port=9132 -Djava.rmi.server.hostname=192.168.24.87
      networks:
         - adopt-network
      command:
        - mkdir  -p /home/adopt/push_notification     
      volumes:
       - /var/lib/docker/containers/adopt:/log
       - adoptbssdoc:/var/document/
       - "/etc/localtime:/etc/localtime:ro"
       - "/root/ssl:/root"
       - "/root/firebase_config:/root/firebase_config"
      logging:
         driver: "json-file"
         options:
           max-size: "10m"
           max-file: "3"
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    revenue:
      container_name: adopt-revenuemanagement-container
      image: adoptnettech/adopt-revenuemanagement-image:V-2.815 #814  #811  #810 #809 #806 #804 #803 #802 #801  #795 #792  #787 #786 #783
      restart: always
      ports:
        - 40081:40081
        - 16224:16224
        - 16225:16225
        - 9129:9129
        - 9130:9130
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptrevenuemanagement?allowPublicKeyRetrieval=true&useSSL=false
        - spring.datasource.username=adoptrevenuemanagement
        - spring.datasource.password=adoptrevenuemanagement@1421
        - server.ssl.enabled=false
        - TZ=Asia/Yangon
        - server.port=40081
        - project.currency=SSP
        - project.currency.cent=Piastres
        - cronjobtimeforrevenueeverydaymidnight=0 55 23 * * ?
        - cronjobtimeforeverymonthfirstday=0 5 0 1 * ?
        - cronjobforgenerateinvoicenumber=0 0/1 * * * ?
        - cronjobforpostpaidinvoicedaymidnight=0 0/1 * * * ?
        - cronJobTimeForAutomatePayment=0 0/1 * * * ?
        - spring.datasource.hikari.maximumPoolSize=300
        - logging.level.root=INFO
        - logging.level.org.apache.tomcat=INFO
        - logging.level.org.springframework.web=INFO
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - postpaid.invoice.day.midnight.isNextBilldate=true
          #- JAVA_OPTS=-Xms16g -Xmx32g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
          #- JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9129 -Dcom.sun.management.jmxremote.rmi.port=9130 -Djava.rmi.server.hostname=192.168.24.87
        - JAVA_OPTS=-'Xms6g -Xmx10g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=4 -XX:G1HeapRegionSize=16m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10 -XX:+UseContainerSupport -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap.hprof -Xlog:gc*,gc+heap=info:file=/tmp/gc.log:time,uptime,level,tags'
        - JAVA_TOOL_OPTIONS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9129 -Dcom.sun.management.jmxremote.rmi.port=9130 -Djava.rmi.server.hostname=192.168.24.87'
        - dbMinPool=50
        - dbMaxPool=300
        - dbIdleTime=15000
      networks:
         - adopt-network
      volumes:
       - /var/lib/docker/containers/adopt:/log
       - /root/docker/newcerti/2023-24:/root/
       - /root/docker/MTN:/home/
       - adoptbssdoc:/var/document/
       - adoptbssdoc1:/var/document/read
       - "/etc/localtime:/etc/localtime:ro"
      deploy:
        resources:
          limits:
            cpus: 6 # Set CPU limit to 4 cores
            memory: 12G  # Set memory limit to 8 gigabytes

    salescrm:
      container_name: adopt-salescrm-container
      image: adoptnettech/adopt-salescrm-image:V-2.167 #161 #156 #153  #151   #145 #140 #139  #135 #134
      restart: always
      ports:
        - 9093:9093
        - 9121:9121
        - 9122:9122
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptsalesscrms?allowPublicKeyRetrieval=true&useSSL=false
        - spring.datasource.username=adoptsalesscrms
        - spring.datasource.password=adoptsalesscrms@1421
        - TZ=Asia/Yangon
        - LIQUIBASE_CATALOG_NAME=adoptsalesscrms
        - logging.level.root=INFO
        - logging.level.com.adopt.salescrmbss=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - JAVA_OPTS=-Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
        - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9121 -Dcom.sun.management.jmxremote.rmi.port=9122 -Djava.rmi.server.hostname=192.168.24.87
      networks:
        - adopt-network
      volumes:
        - adoptbssdoc:/var/document/
        - adoptbssdoc1:/var/document/read
        - /var/lib/docker/containers/adopt:/log
        - "/etc/localtime:/etc/localtime:ro"

    ticket:
      container_name: adopt-ticketmanagement-container
      image: adoptnettech/adopt-ticketmanagement-image:V-2.264 #263 #262 #258 #257 #248 #245 #247 #245 #244 #243 #215  #213 #210
      restart: always
      ports:
        - 30087:30087
        - 9123:9123
        - 9124:9124
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptticketmanagement?allowPublicKeyRetrieval=true&useSSL=false
        - spring.datasource.username=adoptticketmanagement
        - spring.datasource.password=adoptticketmanagement@1421
        - server.ssl.enabled=false
        - TZ=Asia/Yangon
        - server.port=30087
        - cronJobTimeForReassignTicket=0 0/5 * * * ?
        - cronJobTimeForTatMatrix=0 0/1 * * * ?
        - cronJobTimeForReminderTicketFollowUp=0 0/5 * * * ?
        - cronJobTimeForOverDueTicketFollowUp=0 0/5 * * * ?
        - javers.sqlSchemaManagementEnabled=true
          #- mail.imap.username=baglepriyanka555%40gmail.com
          #- mail.imap.password=icdadtvcbgamufpd
          #- enable.mailConfig=true
        - enable.mailConfig1=false
        - mail.imap1.ssl=true
        - mail.imap1.host=imap.gmail.com
        - mail.imap1.port=993
        - mail.imap1.username=testadopt6%40gmail.com
        - mail.imap1.password=fhbmasmngoarpabk
        - enable.mailConfig2=false
        - mail.imap2.ssl=true
        - mail.imap2.host=imap.gmail.com
        - mail.imap2.port=993
          #- mail.imap2.username=testadopt63%40gmail.com
          #- mail.imap2.password=qyxwjhuhkuknplxa
        - logging.level.root=INFO
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
          #- JAVA_OPTS=-Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
          #- JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9123 -Dcom.sun.management.jmxremote.rmi.port=9124 -Djava.rmi.server.hostname=192.168.24.87
        - JAVA_OPTS=-'Xms2g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=4 -XX:G1HeapRegionSize=16m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10 -XX:+UseContainerSupport -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap.hprof -Xlog:gc*,gc+heap=info:file=/tmp/gc.log:time,uptime,level,tags'
        - JAVA_TOOL_OPTIONS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9123 -Dcom.sun.management.jmxremote.rmi.port=9124 -Djava.rmi.server.hostname=192.168.24.87'
        - dbMinPool=50
        - dbMaxPool=300
        - dbIdleTime=15000
      networks:
        - adopt-network
      volumes:
        - /root/docker/:/root/
        - adoptbssdoc:/var/document/
        - adoptbssdoc1:/var/document/read
        - /var/lib/docker/containers/adopt:/log
        - "/etc/localtime:/etc/localtime:ro"
      deploy:
        resources:
          limits:
            cpus: 5 # Set CPU limit to 4 cores
            memory: 6G  # Set memory limit to 8 gigabytes


    task:
      container_name: adopt-taskmanagement-container
      image: adoptnettech/adopt-taskmanagement-image:V-2.33 #28 #27 #24 #19 #16 #8
      restart: always
      ports:
        - 30089:30089
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adopttaskmanagement?allowPublicKeyRetrieval=true&useSSL=false
        - spring.datasource.username=adopttaskmanagement
        - spring.datasource.password=adopttaskmanagement@1421
        - server.ssl.enabled=false
        - TZ=Asia/Yangon
        - server.port=30089
        - cronJobTimeForReassignTicket=0 0/1 * * * ?
        - cronJobTimeForTatMatrix=0 0/1 * * * ?
        - cronJobTimeForReminderTicketFollowUp=0 0/1 * * * ?
        - cronJobTimeForOverDueTicketFollowUp=0 0/1 * * * ?
        - spring.enable.unpickticket.scheduling=false
        - javers.sqlSchemaManagementEnabled=true
        - enable.mailConfig1=false
        - mail.imap1.ssl=false
        - mail.imap1.host=imap.gmail.com
        - mail.imap1.port=993
        - mail.imap1.username=adopttest6email%40gmail.com
        - mail.imap1.password=artrxabwqxuqpmpq
        - enable.mailConfig2=false
        - mail.imap2.ssl=false
        - mail.imap2.host=imap.gmail.com
        - mail.imap2.port=993
        - kafka-url=192.168.24.87:30084
        - mail.imap2.username=logiaca22%40gmail.com
        - mail.imap2.password=jleytxzabivomcoe
        - spring.zipkin.base-url=http://192.168.24.87:9411
        - spring.sleuth.sampler.probability=1
        - logging.level.root=INFO
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=16225 -Dcom.sun.management.jmxremote.rmi.port=16224 -Djava.rmi.server.hostname=192.168.24.87
      networks:
        - adopt-network
      volumes:
       - /root/docker/:/root/
       - adoptbssdoc:/var/document/
       - adoptbssdoc1:/var/document/read
       - /var/lib/docker/containers/adopt:/log
       - "/etc/localtime:/etc/localtime:ro"

    inventory:
      container_name: adopt-inventorymanagement-container
      image: adoptnettech/adopt-inventorymanagement-image:V-2.506 #505 #499 #498 #497 #496 #494 #483 #492 #491 #489 #484 #483 #482 #481 #477 #476 #475 #473 #459 #405 #373       #372 #359 #341 #340 #335 #333 #330
      restart: always
      ports:
        - 30083:30083
        - 9125:9125
        - 9126:9126
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptinventorymanagement?allowPublicKeyRetrieval=true&useSSL=false
        - spring.datasource.username=adoptinventorymanagement
        - spring.datasource.password=adoptinventorymanagement@1421
        - server.ssl.enabled=false
        - TZ=Asia/Yangon
        - server.port=30083
        - cronJobTimeForwarrentydays=59 23 * * * ?
        - logging.level.root=INFO
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - spring.servlet.multipart.max-file-size=10MB
        - spring.servlet.multipart.max-request-size=10MB
        #- JAVA_OPTS=-Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
        #- JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9125 -Dcom.sun.management.jmxremote.rmi.port=9126 -Djava.rmi.server.hostname=192.168.24.214
        - JAVA_OPTS=-'Xms6g -Xmx10g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=4 -XX:G1HeapRegionSize=16m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10 -XX:+UseContainerSupport -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap.hprof -Xlog:gc*,gc+heap=info:file=/tmp/gc.log:time,uptime,level,tags'
        - JAVA_TOOL_OPTIONS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9125 -Dcom.sun.management.jmxremote.rmi.port=9126 -Djava.rmi.server.hostname=192.168.24.87'
        - dbMinPool=50
        - dbMaxPool=300
        - dbIdleTime=15000
      networks:
         - adopt-network
      volumes:
       - /root/docker/:/root/
       - adoptbssdoc:/var/document/
       - adoptbssdoc1:/var/document/read
       - /var/lib/docker/containers/adopt:/log
       - "/etc/localtime:/etc/localtime:ro"
      deploy:
        resources:
          limits:
            cpus: 8 # Set CPU limit to 4 cores
            memory: 12G  # Set memory limit to 8 gigabytes

    integration:
      container_name: adopt-integration-container
      image: adoptnettech/adopt-integrationsystem-image:V-2.558 #543 #540 #522 #515 #493 #489  #482  #447 #422   #403 #399  #390 #389 #387 #380 #375 #374
      restart: always
      ports:
        - 41080:41080
        - 9133:9133
        - 9134:9134
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptintegrationsystem?allowPublicKeyRetrieval=true&useSSL=false
        - spring.datasource.username=adoptintegrationsystem
        - spring.datasource.password=adoptintegrationsystem@1421
        - cronjobtimeforairtelpaymentstatus=0 0/20 * * * ?
        - TZ=Asia/Yangon
        - serverIpForAudit=192.168.24.87
        - momo.scheduled.time=1
        - server.port=41080
        - environmentInfo="Production"
        - logging.level.root=DEBUG
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - JAVA_OPTS=-Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
        - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9133 -Dcom.sun.management.jmxremote.rmi.port=9134 -Djava.rmi.server.hostname=192.168.24.87
      volumes:
        - adoptbssdoc:/var/document/
        - adoptbssdoc1:/var/document/read
        - /var/lib/docker/containers/adopt:/log
        - "/etc/localtime:/etc/localtime:ro"
        - "/root/ssl/:/root"
      networks:
        - adopt-network
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    radius:
      container_name: adopt-radius-container
      image: adoptnettech/adopt-radius-image:V-2.868 #854 #844 #831 #809 #785 #783 #776
      restart: always
      ports:
        - 9090:9090
        - 1812:1812/udp
        - 1813:1813/udp
        - 162:161/udp
        - 3799:3799/udp
        - 9127:9127
        - 9128:9128
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - kafka-url=192.168.24.87:30084
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptradiusbss?allowPublicKeyRetrieval=true&useSSL=false
        - spring.datasource.username=adoptradiusbss
        - spring.datasource.password=adoptradiusbss
        - server.ssl.enabled=false
          #- server.port=9091
        - spring.jpa.show-sql=false
        - session.prune.cron.schedule=0 */15 * ? * *
        - spring.redis.host=192.168.24.87
        - spring.jpa.properties.hibernate.format_sql=false
        - spring.enable.planexpiry.scheduling= true
        - radius.postpaid.plan.expiry.schedule=0 05 17 1 12 ?
        - TZ=Asia/Yangon
        - radius.authentication.type=dependent
        - logging.level.root=INFO
        - logging.level.com.adopt=DEBUG
        - logging.level.org.apache.kafka=WARN
        - logging.level.org.springframework.kafka=WARN
        - authMinPort=500
        - authMaxPort=500
        - acctMinPort=500
        - acctMaxPort=500
        - dbMinPool=250
        - dbMaxPool=250
        - dbIdleTime=2000
        - redis.sentinel.master=mymaster
        - redis.sentinel.nodes=192.168.24.87:26379
        - JAVA_OPTS=-Xms16g -Xmx32g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=4 -XX:ConcGCThreads=2 -XX:G1HeapRegionSize=32m -XX:InitiatingHeapOccupancyPercent=45 -XX:G1ReservePercent=10
        - JAVA_TOOL_OPTIONS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9127 -Dcom.sun.management.jmxremote.rmi.port=9128 -Djava.rmi.server.hostname=192.168.24.87
      networks:
        - adopt-network
      command:
        - mkdir -p /var/document/bulkvlanpath
      volumes:
        - adoptbssdoc:/var/document/
        - adoptbssdoc1:/var/document/read
        - /var/lib/docker/containers/adopt:/log
        - "/etc/localtime:/etc/localtime:ro"
        - "/root/ssl:/root"
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    grafana:
      container_name: adopt-grafana-container
      image: grafana/grafana:latest
      restart: always
      ports:
        - 3000:3000
      volumes:
        - grafana-storage:/var/lib/grafana
        - /etc/localtime:/etc/localtime:ro
        - /root/docker/newcerti:/etc/certi
      environment:
        - TZ=Asia/Yangon
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=p@ssw0rd
        - GF_SERVER_DOMAIN=smtp.office365.com
        - GF_SMTP_ENABLED=true
        - GF_SMTP_HOST=smtp.office365.com:587
        - GF_SMTP_USER=notification@adoptnet.tech
        - GF_SMTP_PASSWORD=ADOPT#1421@SUPPORT
        - GF_SMTP_FROM_ADDRESS=notification@adoptnet.tech
        # - GF_SERVER_PROTOCOL=https
        # - GF_SERVER_CERT_KEY=/etc/certi/server.key
        # - GF_SERVER_CERT_FILE=/etc/certi/server.crt
      networks:
        - adopt-network
      depends_on:
        - prometheus

    prometheus:
     container_name: adopt-prometheus-container
     image: adoptnettech/prometheus:latest
     expose:
       - 9098
     ports:
       - 9098:9090
     volumes:
       - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
       - prometheus-storage:/prometheus
       - "/etc/localtime:/etc/localtime:ro"
     networks:
       - adopt-network


    gui:
      container_name: adopt-gui-container
      image: adoptnettech/adopt-ui-image:V-2.1493  #1489 #1488 #1485 #1482  #1479  #1472   #1471  #1470   #1463 #1462  #1458 #1450 #1446 #1430 #1424 #1423 #1421 #1420 #1419 #1418 #1417 #1414 #1413 #1410 #1406 #1400 #1373 #1397 #1396 #1394 #1393 #1390 #1388 #1387 #1380 #1379 #1375 #1373 #1371 #1370 #1363 #1355 #1351 #1243 #1167   #V-2.1162   #1150     #1113 #1111     #1108 #1083 #999 #992 #995 
      restart: always
      ports:
        - 4200:80
      environment:
        - ADOPT_API_GATEWAY_COMMON_PORT=https://uat-apigatewaycommon.ananda.com.mm
          #- APIGATEWAY_IP_PORT=192.168.24.87:40042
        - INDEPENDENT_AAA=false
        - LOGIN_CAPTCHA=false
        - COUNTRY_ID=11
        - STATE_ID=9
        - CITY_ID=8
        - PINCODE_ID=8
        - SERVICEAREA_ID=14
        - AREA_ID=8
        - GOOGLE_MAPS_API_KEY=AIzaSyBJMMItJT9bMQlbJK8RnXhHi5rLrICje0s
        - TZ=Asia/Yangon
      networks:
        - adopt-network
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
      # - /root/docker/newcerti:/etc/certi
      #   - "/root/docker/MTN/MTN_logo1.jpg:/usr/share/nginx/html/assets/img/loginlogo.jpg"
      #   - "/root/docker/MTN/loginbg.jpg:/usr/share/nginx/html/assets/img/loginbg.jpg"
      #   - "/root/docker/MTN/MTN_logo1.png:/usr/share/nginx/html/assets/img/adopt_logo.png"
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    pms:
      container_name: adopt-partnermanagement-container
      image: adoptnettech/adopt-partnermanagement-image:V-2.126 #123 #120   #119 #114
      restart: always
      ports:
        - 40082:40082
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.24.87:8761/eureka
        - eureka.instance.ip-address=192.168.24.87
        - spring.datasource.url=jdbc:mysql://192.168.24.87:3306/adoptpartnermanagement?allowPublicKeyRetrieval=true&useSSL=false
        - spring.datasource.username=adoptpartnermanagement
        - spring.datasource.password=adoptpartnermanagement@1421
        - SPRING.RABBITMQ.HOST=192.168.24.87
        - server.ssl.enabled=false
        - server.port=40082
        - logging.level.com.adopt==DEBUG
        - TZ=Asia/Kolkata
        - kafka-url=192.168.24.87:30084
      command:
        - mkdir -p /var/document/partnerdoc

      networks:
        - adopt-network
      volumes:
        - /var/lib/docker/containers/adopt:/log
       #- /root/docker/:/root/
       #- adoptbssdoc:/var/document/
        - "/etc/localtime:/etc/localtime:ro"

    cwsc_ananda:
      container_name: adopt-cwsc_ananda-container
      image: adoptnettech/adopt-adoptcwsc-image:V-2.462  #461 #459 #458  #457 #453  #451 #444 #442 #441 #439 #427 #414 #398 #397    #364   #339  #318 #307 #295   #270 #264   #257  #255 #250 #247 #245
      restart: always
      ports:
        - 4201:80
      environment:
        - APIGATEWAY_IP_PORT=https://uat-apigatewaycommon.ananda.com.mm
        - ADOPTBOT=192.168.24.87:5000
        - BILLINGENGINE_COMMON_IP_PORT=192.168.24.87:40080
        - PROVISIONING_PORTAL=192.168.24.87:4210
        - USERNAME=admin@Ananda
        - PASSWORD=Adopt@1421
        - TZ=Asia/Yangon
        # - FACEBOOK_LINK=https://www.facebook.com/MTNSSD?mibextid=LQQJ4d
        # - TWITTER_LINK=https://twitter.com/MTNSSD
        # - LINKEDIN_LINK=https://www.linkedin.com/company/mtn-south-sudan/
        # - FREE_PLAN=20
        # - TIMER_COUNT=30
      networks:
        - adopt-network
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        #- /root/docker/newcerti:/etc/certi
        - "/root/docker/logo/viber_image_2025-05-23_16-28-02-154.jpg:/usr/share/nginx/html/assets/img/loginlogo.jpg"
        - "/root/docker/logo/viber_image_2025-05-23_22-41-01-004.jpg:/usr/share/nginx/html/assets/img/savanna_bg.jpg"
        - "/root/docker/logo/viber_image_2025-05-23_16-27-17-211.png:/usr/share/nginx/html/assets/img/adopt_logo.png"
        - "/root/docker/logo/viber_image_2025-05-23_22-41-01-004.jpg:/usr/share/nginx/html/savanna_bg.78b10f4603404fac4628.jpg"
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    cwsc_tutu:
      container_name: adopt-cwsc_tutu-container
      image: adoptnettech/adopt-adoptcwsc-image:V-2.462  #459  #458 #453 #451 #442 #441 #439 #427 #398
        #364 #318 #307
       #270 #253 #250 #247 #245 #244 #238 #231 #217 #213 #201
      restart: always
      ports:
        - 4202:80
      environment:
        - APIGATEWAY_IP_PORT=192.168.24.87:30085
        - ADOPTBOT=192.168.24.87:5000
        - BILLINGENGINE_COMMON_IP_PORT=192.168.24.87:40080
        - PROVISIONING_PORTAL=192.168.24.87:4210
        - USERNAME=admin@TuTu
        - PASSWORD=Adopt@1421
        - TZ=Asia/Yangon
        # - FACEBOOK_LINK=https://www.facebook.com/MTNSSD?mibextid=LQQJ4d
        # - TWITTER_LINK=https://twitter.com/MTNSSD
        # - LINKEDIN_LINK=https://www.linkedin.com/company/mtn-south-sudan/
        # - FREE_PLAN=20
        # - TIMER_COUNT=30
      networks:
        - adopt-network
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/root/docker/logo/TuTu.png:/usr/share/nginx/html/assets/img/loginlogo.jpg"
        #- /root/docker/newcerti:/etc/certi
        # - "/root/docker/MTN/MTN_logo1.jpg:/usr/share/nginx/html/assets/img/loginlogo.jpg"
        - "/root/docker/HTICL/images/loginbg.jpg:/usr/share/nginx/html/assets/img/savanna_bg.jpg"
        - "/root/docker/logo/TuTu.png:/usr/share/nginx/html/assets/img/adopt_logo.png"
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    cwsc_hi:
      container_name: adopt-cwsc_hi-container
      image: adoptnettech/adopt-adoptcwsc-image:V-2.462  #459  #458 #442 #414 #398
        #318 #310 #270 #253 #250 #247 #245 #244 #238 #231 #217 #213 #201
      restart: always
      ports:
        - 4203:80
      environment:
        - APIGATEWAY_IP_PORT=192.168.24.87:30085
        - ADOPTBOT=192.168.24.87:5000
        - BILLINGENGINE_COMMON_IP_PORT=192.168.24.87:40080
        - PROVISIONING_PORTAL=192.168.24.87:4210
        - USERNAME=admin@HTI
        - PASSWORD=Adopt@1421
        - TZ=Asia/Yangon
        # - FACEBOOK_LINK=https://www.facebook.com/MTNSSD?mibextid=LQQJ4d
        # - TWITTER_LINK=https://twitter.com/MTNSSD
        # - LINKEDIN_LINK=https://www.linkedin.com/company/mtn-south-sudan/
        # - FREE_PLAN=20
        # - TIMER_COUNT=30
      networks:
        - adopt-network
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        #- /root/docker/newcerti:/etc/certi
        - "/root/docker/logo/HiInternet.png:/usr/share/nginx/html/assets/img/loginlogo.jpg"
        #- "/root/docker/MTN/M:/usr/share/nginx/html/assets/img/loginlogo.jpg"
        - "/root/docker/HTICL/images/loginbg.jpg:/usr/share/nginx/html/assets/img/savanna_bg.jpg"
        - "/root/docker/logo/HiInternet.png:/usr/share/nginx/html/assets/img/adopt_logo.png"
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    cwsc_vnet:
      container_name: adopt-cwsc_vnet-container
      image: adoptnettech/adopt-adoptcwsc-image:V-2.462  #459  #458 #442 #414 #398 #318 #307 #270 #253 #250 #247 #245 #244 #238 #231 #217 #213 #201
      restart: always
      ports:
        - 4204:80
      environment:
        - APIGATEWAY_IP_PORT=192.168.24.87:30085
        - ADOPTBOT=192.168.24.87:5000
        - BILLINGENGINE_COMMON_IP_PORT=192.168.24.87:40080
        - PROVISIONING_PORTAL=192.168.24.87:4210
        - USERNAME=admin@VNET
        - PASSWORD=Adopt@1421
        - TZ=Asia/Yangon
        # - FACEBOOK_LINK=https://www.facebook.com/MTNSSD?mibextid=LQQJ4d
        # - TWITTER_LINK=https://twitter.com/MTNSSD
        # - LINKEDIN_LINK=https://www.linkedin.com/company/mtn-south-sudan/
        # - FREE_PLAN=20
        # - TIMER_COUNT=30
      networks:
        - adopt-network
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/root/docker/logo/Vnets.png:/usr/share/nginx/html/assets/img/loginlogo.jpg"
        #- /root/docker/newcerti:/etc/certi
        #- "/root/docker/MTN/MTN_logo1.jpg:/usr/share/nginx/html/assets/img/loginlogo.jpg"
        - "/root/docker/HTICL/images/loginbg.jpg:/usr/share/nginx/html/assets/img/savanna_bg.jpg"
        - "/root/docker/logo/Vnets.png:/usr/share/nginx/html/assets/img/adopt_logo.png"
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    cwsc_web_ananda:
      container_name: adopt-cwsc-web-ananda-container
      image: adoptnettech/adopt-cwsc-web:V-2.52  #51  #48 #45 #43 #42 #38 #37 #30 #29 #28 #26 #24  #459  #458 #442 #414 #398 #318 #307 #244 #238 #231 #217 #213 #201
      restart: always
      ports:
        - 4204:80
      environment:
        - MAIN_URL=192.168.24.87:30085
          #- APIGATEWAY_IP_PORT=192.168.24.87:30085
        - ADOPTBOT=192.168.24.87:5000
          #- BILLINGENGINE_COMMON_IP_PORT=192.168.24.87:40080
          #- PROVISIONING_PORTAL=192.168.24.87:4210
        - USERNAME=admin@ananda
        - PASSWORD=Adopt@1421
        - TZ=Asia/Yangon
          #- FACEBOOK_LINK=https://www.facebook.com/MTNSSD?mibextid=LQQJ4d
          #- TWITTER_LINK=https://twitter.com/MTNSSD
          #- LINKEDIN_LINK=https://www.linkedin.com/company/mtn-south-sudan/
          #- FREE_PLAN=20
          #- TIMER_COUNT=30
      networks:
        - adopt-network
          #volumes:
          #- /root/branding/ananda/config.json:/usr/share/nginx/html/assets/assets/config/config.json
          #- "/etc/localtime:/etc/localtime:ro"
          #- "/root/docker/logo/Vnets.png:/usr/share/nginx/html/assets/img/loginlogo.jpg"
          #- /root/docker/newcerti:/etc/certi
          # - "/root/docker/MTN/MTN_logo1.jpg:/usr/share/nginx/html/assets/img/loginlogo.jpg"
          #- "/root/docker/HTICL/images/loginbg.jpg:/usr/share/nginx/html/assets/img/savanna_bg.jpg"
          #- "/root/docker/logo/Vnets.png:/usr/share/nginx/html/assets/img/adopt_logo.png"
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes				
    filebeat:
      container_name: filebeat
      image: adoptnettech/adopt-filebeat:filebeat
      restart: on-failure
      networks:
        - adopt-network
      volumes:
        - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker/containers/adopt:/var/lib/docker/containers/adopt:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./filebeat/data:/usr/share/filebeat/data:rw
      user: root
      command: ./filebeat -e -strict.perms=false
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    logstash:
      container_name: logstash
      image: adoptnettech/adopt-logstash:logstash
      ports:
        - 25826:25826
        - 5040:5044
      volumes:
        - /root/logstash/pipeline:/usr/share/logstash/pipeline:ro
      restart: on-failure
      networks:
        - adopt-network
      depends_on:
        - elasticsearch
      environment:
        - xpack.monitoring.elasticsearch.url=192.168.24.87:9200  # Set Elasticsearch host URL
        - xpack.monitoring.elasticsearch.username=elastic
        - xpack.monitoring.elasticsearch.password=adopt@123   # Same password as Kibana and Elasticsearch
        - xpack.monitoring.enabled=true
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    elasticsearch:
      container_name: elasticsearch
      image: adoptnettech/adopt-elasticsearch:elasticsearch
      logging:
         driver: "json-file"
         options:
           max-size: "10m"
           max-file: "3"
      restart: on-failure
      ports:
        - "9200:9200"
      networks:
        - adopt-network
      environment:
        - xpack.security.enabled=true  # Enable security for Elasticsearch
        - discovery.type=single-node
        - xpack.security.audit.enabled=true
        - ELASTIC_PASSWORD=adopt@123  # Password for the 'adminadopt' superuser
      volumes:
        - /root/elasticsearch/data:/root/home/elasticsearch/data:rw
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    kibana:
      container_name: kibana
      image: adoptnettech/adopt-kibana:adopt-kibana
      ports:
        - "5601:5601"
      networks:
        - adopt-network
      restart: on-failure
      logging:
         driver: "json-file"
         options:
           max-size: "10m"
           max-file: "3"
      links:
        - elasticsearch
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_URL=192.168.24.87:9200
        - ELASTICSEARCH_USERNAME=elastic  # Username for Kibana to authenticate with Elasticsearch
        - ELASTICSEARCH_PASSWORD=adopt@123  # Password for the 'adminadopt' user
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes


    cadvisor:
      image: adoptnettech/cadvisor:v0.49.1
      container_name: cadvisor
      ports:
        - 8080:8080
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
      devices:
        - /dev/kmsg
      restart: always
      networks:
        - adopt-network
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    redis-master:
      image: redis:latest
      container_name: redis-master
      ports:
        - "6379:6379"
      volumes:
        - /root/redis-data/master:/data:rw
      command: ["redis-server", "--appendonly", "yes"]
      environment:
        - TZ=Africa/Kampala
      networks:
        - adopt-network
      restart: always
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    redis-sentinel:
      image: redis:latest
      container_name: redis-sentinel
      command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
      volumes:
        - /root/sentinel:/etc/redis
      environment:
        - TZ=Africa/Kampala
      ports:
        - "26379:26379"
      networks:
        - adopt-network
      restart: always
      #deploy:
            #resources:
                #limits:
                    #cpus: 2 # Set CPU limit to 4 cores
                    #memory: 4G  # Set memory limit to 8 gigabytes

    adopt-chatbot:
      image: adoptnettech/adopt.chatbot-image:V-2.32 #30 #23 #18 #12 # <-- use the correct chatbot image version
      container_name: adopt-chatbot-app
      ports:
        - "5000:5000"
      environment:
        - APP_PORT=5000
        - COMMON_API_GATEWAY=http://192.168.24.87:30085 #{GUI Url along with common port}
        - FRONTEND_UI=http://192.168.24.87:4200  #{GUI Url}
        - BSS_USERNAME=admin@Ananda #{ISP Username (in which isp you want to integrate chatbot) }
        - BSS_PASSWORD=Adopt@1421  #{ISP Password (Configured ISPs Password) }
        - BRANCHID-1  # <-- Ensure this branch ID is created and set correctly
        - SERVICEAREA=5 # <-- Ensure this service area is created and set correctly
        - LEADSOURCEID=2  # <-- Ensure this lead source ID is created and set correctly

volumes:
   adoptbssdoc:
   adoptbssdoc1:
   dbdata:
   prometheus-storage:
   grafana-storage:
   kafka:
   zookeeper:
networks:
  adopt-network:
